<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>GameBoxSetup</AssemblyName>
    <RootNamespace>GameBoxSetup</RootNamespace>
    <Version>2.0.0</Version>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <NoWarn>WFO1000;CS8618</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="package.zip">
      <LogicalName>GameBoxSetup.package.zip</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
